// demos/salt-theme-gen/css-in-js/src/App.tsx
import { useState } from 'react';
import styled, { ThemeProvider } from 'styled-components';
import { theme, styledTheme } from './theme';

const Root = styled.div`
  font-family: system-ui, sans-serif;
  padding: var(--space-xl);
  background: var(--color-background);
  color: var(--color-text);
  min-height: 100vh;
`;

const Heading = styled.h1`
  font-size: var(--text-xl);
  margin-bottom: var(--space-sm);
  margin-top: 0;
`;

const Muted = styled.p`
  color: var(--color-muted);
  font-size: var(--text-sm);
  margin-bottom: var(--space-lg);
`;

const Button = styled.button`
  background: ${({ theme }) => theme.colors.primary};
  color: ${({ theme }) => theme.colors.onPrimary};
  border: none;
  padding: var(--space-sm) var(--space-md);
  border-radius: var(--radius-md);
  cursor: pointer;
  font-size: var(--text-sm);
  margin-bottom: var(--space-xl);
`;

const Card = styled.div`
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--space-lg);
  margin-bottom: var(--space-lg);
`;

const CardHeading = styled.h2`
  font-size: var(--text-md);
  margin-top: 0;
  margin-bottom: var(--space-md);
`;

const Swatches = styled.div`
  display: flex;
  gap: var(--space-sm);
  flex-wrap: wrap;
`;

const Swatch = styled.div<{ $color: string }>`
  width: 48px;
  height: 48px;
  border-radius: var(--radius-sm);
  background: ${p => p.$color};
  border: 1px solid var(--color-border);
`;

const colors = Object.entries(theme.light.colors);
const spacing = Object.entries(theme.light.spacing);

export function App() {
  const [mode, setMode] = useState<'light' | 'dark'>('light');

  const toggle = () => {
    const next = mode === 'light' ? 'dark' : 'light';
    setMode(next);
    document.documentElement.setAttribute('data-theme', next);
    localStorage.setItem('theme', next);
  };

  return (
    <ThemeProvider theme={styledTheme}>
      <Root>
        <Heading>salt-theme-gen — styled-components</Heading>
        <Muted>Preset: ocean &nbsp;·&nbsp; {mode} mode &nbsp;·&nbsp; typed theme props via module augmentation</Muted>

        <Button onClick={toggle}>Toggle dark mode</Button>

        <Card>
          <CardHeading>Color palette ({colors.length} colors)</CardHeading>
          <Swatches>
            {colors.map(([name, value]) => (
              <Swatch key={name} $color={value} title={`${name}: ${value}`} />
            ))}
          </Swatches>
        </Card>

        <Card>
          <CardHeading>Spacing scale</CardHeading>
          {spacing.map(([k, v]) => (
            <div key={k} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
              <span style={{ width: 40, fontSize: 12, color: 'var(--color-muted)' }}>{k}</span>
              <div style={{ height: 4, background: 'var(--color-primary)', width: (v as number) * 1.5 }} />
              <span style={{ fontSize: 12, color: 'var(--color-muted)' }}>{v}px</span>
            </div>
          ))}
        </Card>
      </Root>
    </ThemeProvider>
  );
}

// demos/salt-theme-gen/nuxt/app.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { generateTheme } from 'salt-theme-gen';

const theme = generateTheme({ preset: 'ocean' });
const colors = Object.entries(theme.light.colors);
const spacing = Object.entries(theme.light.spacing);
const mode = ref<'light' | 'dark'>('light');

onMounted(() => {
  const stored = localStorage.getItem('theme');
  if (stored === 'dark') mode.value = 'dark';
});

function toggle() {
  const next = mode.value === 'light' ? 'dark' : 'light';
  mode.value = next;
  document.documentElement.setAttribute('data-theme', next);
  localStorage.setItem('theme', next);
}
</script>

<template>
  <NuxtRouteAnnouncer />
  <div class="root">
    <h1>salt-theme-gen — Nuxt</h1>
    <p class="muted">Preset: ocean &nbsp;·&nbsp; {{ mode }} mode</p>
    <button class="btn" @click="toggle">Toggle dark mode</button>

    <div class="card">
      <h2>Color palette ({{ colors.length }} colors)</h2>
      <div class="swatches">
        <div v-for="[name, value] in colors" :key="name" class="swatch" :style="{ background: value }" :title="`${name}: ${value}`" />
      </div>
    </div>

    <div class="card">
      <h2>Spacing scale</h2>
      <div v-for="[k, v] in spacing" :key="k" class="spacing-row">
        <span class="spacing-label">{{ k }}</span>
        <div class="spacing-bar" :style="{ width: `${(v as number) * 1.5}px` }" />
        <span class="spacing-value">{{ v }}px</span>
      </div>
    </div>
  </div>
</template>

<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
.root { font-family: system-ui, sans-serif; padding: var(--space-xl, 32px); background: var(--color-background, #fff); color: var(--color-text, #111); min-height: 100vh; }
h1 { font-size: var(--text-xl, 20px); margin-bottom: var(--space-sm, 8px); }
h2 { font-size: var(--text-md, 16px); margin-bottom: var(--space-md, 16px); }
.muted { color: var(--color-muted, #666); font-size: var(--text-sm, 14px); margin-bottom: var(--space-lg, 24px); }
.btn { background: var(--color-primary, #2563eb); color: var(--color-on-primary, #fff); border: none; padding: var(--space-sm, 8px) var(--space-md, 16px); border-radius: var(--radius-md, 8px); cursor: pointer; font-size: var(--text-sm, 14px); margin-bottom: var(--space-xl, 32px); }
.card { background: var(--color-surface, #f5f5f5); border: 1px solid var(--color-border, #e0e0e0); border-radius: var(--radius-lg, 12px); padding: var(--space-lg, 24px); margin-bottom: var(--space-lg, 24px); }
.swatches { display: flex; gap: var(--space-sm, 8px); flex-wrap: wrap; }
.swatch { width: 48px; height: 48px; border-radius: var(--radius-sm, 4px); border: 1px solid var(--color-border, #e0e0e0); }
.spacing-row { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }
.spacing-label { width: 40px; font-size: 12px; color: var(--color-muted, #666); }
.spacing-bar { height: 4px; background: var(--color-primary, #2563eb); }
.spacing-value { font-size: 12px; color: var(--color-muted, #666); }
</style>
